[package]
name = "ib_tws_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
bit = "0.1"
ordered-float = "3"
approx = "0.5"
memchr = "2"

futures = "0.3"

thiserror = "1"
miette = "5"
