[package]
name = "ib_tws_tokio"
version = "0.1.0-alpha.1"
edition = "2021"
readme = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ib_tws_core = "0.1.0-alpha"
